using System.IO;
using Content.Client._Forge.DiscordAuth;
using Content.Shared._Forge.DiscordAuth;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._RAT.Donation;

[GenerateTypedNameReferences]
public sealed partial class DonationPanel : Control
{
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly DiscordAuthManager _discordAuth = default!;
    [Dependency] private readonly IClientNetManager _net = default!;

    private bool _isUpdating = false;

    public DonationPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DonationTabs.SetTabTitle(0, "Информация");
        DonationTabs.SetTabTitle(1, "Уровни");
        DonationTabs.SetTabTitle(2, "Discord");

        LoadText(InfoText, "/Credits/don-info.txt");
        LoadText(LevelsText, "/Credits/don-lvl.txt");
        LoadText(DiscordText, "/Credits/don-discord.txt");

        // Безопасно подписываемся на ответ от сервера
        _net.RegisterNetMessage<MsgDiscordStatusResponse>(HandleStatusResponse);

        var uriOpener = IoCManager.Resolve<IUriOpener>();
        var donateUrl = "https://ss14.art"; 

        BuyButtonLevels.OnPressed += _ => uriOpener.OpenUri(donateUrl);
        
        DiscordAuthButton.OnPressed += _ => 
        {
            if (!string.IsNullOrEmpty(_discordAuth.AuthLink))
                uriOpener.OpenUri(_discordAuth.AuthLink);
        };

        RefreshStatusButton.OnPressed += _ => UpdateDiscordStatus();

        UpdateDiscordStatus();
    }

    public void UpdateDiscordStatus()
    {
        if (_isUpdating) return;
        _isUpdating = true;
        
        RefreshStatusButton.Disabled = true;
        RefreshStatusButton.Text = "Запрос к серверу...";

        _net.ClientSendMessage(new MsgDiscordAuthCheck());
    }

    private void HandleStatusResponse(MsgDiscordStatusResponse msg)
    {
        _isUpdating = false;
        RefreshStatusButton.Disabled = false;
        RefreshStatusButton.Text = "Обновить статус";

        if (msg.IsLinked)
            ShowLinked(msg.DiscordId);
        else
            ShowUnlinked();
    }

    private void ShowLinked(string discordId)
    {
        DiscordUnlinkedState.Visible = false;
        DiscordLinkedState.Visible = true;
        
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow("Discord привязка - [color=#4dd883]Активна[/color]");
        DiscordStatusLabel.SetMessage(msg);
        
        DiscordUserLabel.Text = $"Discord: {discordId}";
    }

    private void ShowUnlinked()
    {
        DiscordLinkedState.Visible = false;
        DiscordUnlinkedState.Visible = true;
        
        if (_discordAuth.QrCodeTexture != null)
        {
            DiscordQr.Visible = true;
            DiscordQr.Texture = _discordAuth.QrCodeTexture;
        }
        else
        {
            DiscordQr.Visible = false;
        }
    }

    private void LoadText(RichTextLabel label, string path)
    {
        if (!_resCache.ContentFileExists(path)) return;
        
        try
        {
            using var stream = _resCache.ContentFileRead(path);
            using var reader = new StreamReader(stream);
            var text = reader.ReadToEnd();
            
            if (FormattedMessage.TryFromMarkup(text, out var msg))
                label.SetMessage(msg);
            else
                label.SetMessage(text);
        }
        catch (Exception e)
        {
            Logger.GetSawmill("donation_panel").Error($"Failed to load {path}: {e}");
        }
    }
}