using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class MassCloakConsoleWindow : FancyWindow,
    IComputerWindow<MassCloakConsoleBoundUserInterfaceState>
{
    private readonly ButtonGroup _massCloakButtonGroup = new();
    public event Action<bool>? MassCloak;
    public event Action<float>? MassCloakRangeChanged;

    public MassCloakConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        MassCloakOnButton.Group = _massCloakButtonGroup;
        MassCloakOffButton.Group = _massCloakButtonGroup;
        MassCloakOnButton.OnPressed += _ => MassCloak?.Invoke(true);
        MassCloakOffButton.OnPressed += _ => MassCloak?.Invoke(false);

        MassCloakRangeSlider.OnValueChanged += args =>
        {
            MassCloakRangeValue.Text = ((int)args.Value).ToString();
            MassCloakRangeChanged?.Invoke(args.Value);
        };
    }

    public void UpdateState(MassCloakConsoleBoundUserInterfaceState state)
    {
        MassCloakRangeSlider.MinValue = state.MassCloakMinRange;
        MassCloakRangeSlider.MaxValue = state.MassCloakMaxRange;
        MassCloakRangeSlider.SetValueWithoutEvent(state.MassCloakRange);

        MassCloakRangeValue.Text = ((int)state.MassCloakRange).ToString();

        if (state.MassCloakEnabled)
        {
            MassCloakOnButton.Pressed = true;
        }
        else
        {
            MassCloakOffButton.Pressed = true;
        }
    }
}
