using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private EntityUid? _previewDummy;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
            _entManager.DeleteEntity(_previewDummy.Value);

        _previewDummy = uid;
        ViewBox.DisposeAllChildren();

        var spriteView = new SpriteView
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Scale = new Vector2(8f, 8f),
            OverrideDirection = Direction.South,
            SetSize = new Vector2(350, 500) 
        };
        
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy.Value);
            _previewDummy = null;
        }
    }
}