using System;
using Content.Client.Administration.UI;
using Content.Client.Changelog;
using Content.Client.Credits;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared._Forge.DiscordAuth;
using Content.Client.UserInterface.Systems.Info;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Client._RAT.Donation; // ratgore: sponsor
using Content.Client._Forge.DiscordAuth;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Network;
using Robust.Shared.Localization;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IClientNetManager _netManager = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(RootContainer, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(MainContainer, LayoutContainer.LayoutPreset.Wide);

            LobbySong.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("lobby-state-song-no-song-text")));
            LobbyBackground.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("lobby-state-background-no-background-text")));

            // ratgore start: sponsor
            var donPanel = new DonationPanel();
            DonationAnchor.AddChild(donPanel);
            // ratgore end

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");

            OptionsButton.OnPressed += _ => 
                UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CreditsButton.OnPressed += _ => new CreditsWindow().OpenCentered();

            GuidebookButton.OnPressed += _ => 
                UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();

            RulesButton.OnPressed += _ => 
                UserInterfaceManager.GetUIController<InfoUIController>().OpenWindow();

            AHelpButton.OnPressed += _ => _consoleHost.ExecuteCommand("bahelp");

            DiscordRelinkButton.OnPressed += _ =>
            {
                _netManager.ClientSendMessage(new MsgDiscordAuthRequest());
            };

            CharacterSetupButton.OnPressed += _ => SwitchState(LobbyGuiState.CharacterSetup);
            
            Changelog.OnPressed += _ => 
                UserInterfaceManager.GetUIController<ChangelogUIController>().ToggleWindow();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = (state == LobbyGuiState.Default);
            CharacterSetupState.Visible = (state == LobbyGuiState.CharacterSetup);

            if (state == LobbyGuiState.CharacterSetup)
            {
                UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
            }
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup,
        }
    }
}